name: Drewko
favicon: null
layout_spectrum: 0.5775366947054863
typography_spectrum: 0.8804897926747799
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.1755073769018054
  lightness: 0.6260924071539193
  saturation: 0.3315200961660594
  rhythmicContrast: 0.3417454343289137
purpose: []
